export const exercisesData = {
  Chest: [
    "Bench Press",
    "Incline Dumbbell Press",
    "Chest Fly",
    "Push-ups",
    "Dumbbell Pullover",
    "Chest Dip",
    "Cable Chest Press",
    "Machine Chest Press",
    "Pec Deck Machine",
    "Landmine Chest Press",
  ],
  Back: [
    "Deadlift",
    "Pull-ups",
    "Lat Pulldown",
    "Bent-over Row",
    "Seated Row",
    "T-Bar Row",
    "Chest-supported Row",
    "Single-arm Dumbbell Row",
    "Wide-grip Pulldown",
    "Face Pulls",
  ],
  Triceps: [
    "Triceps Pushdown",
    "Dips",
    "Overhead Triceps Extension",
    "Skull Crushers",
    "Close-grip Bench Press",
    "Triceps Kickback",
    "Cable Overhead Triceps Extension",
    "Diamond Push-ups",
    "Triceps Dips Machine",
    "Barbell Triceps Extension",
  ],
  Biceps: [
    "Bicep Curl",
    "Hammer Curl",
    "Concentration Curl",
    "Preacher Curl",
    "Barbell Curl",
    "Dumbbell Curl",
    "Incline Dumbbell Curl",
    "Cable Curl",
    "Zottman Curl",
    "Chin-ups",
  ],
  Legs: [
    "Squats",
    "Leg Press",
    "Lunges",
    "Deadlifts",
    "Leg Curls",
    "Bulgarian Split Squat",
    "Hip Thrusts",
    "Leg Extensions",
    "Calf Raises",
    "Sumo Squats",
  ],
  Shoulders: [
    "Overhead Press",
    "Lateral Raise",
    "Front Raise",
    "Arnold Press",
    "Upright Row",
    "Dumbbell Shoulder Press",
    "Cable Lateral Raise",
    "Reverse Pec Deck",
    "Face Pulls",
    "Seated Dumbbell Press",
  ],
  Abs: [
    "Plank",
    "Crunches",
    "Leg Raises",
    "Russian Twists",
    "Mountain Climbers",
    "Hanging Leg Raises",
    "Flutter Kicks",
    "Bicycle Crunches",
    "V-ups",
    "Side Plank",
  ],
};

export const daysOfWeek = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
];
